- hosts: localhost
  vars:
    nexus_version: 2.7.0  
    nexus_download_url: https://download.sonatype.com/nexus/nexus-professional-bundle-latest.tar.gz
    nexus_download_dest: /home/ubuntu/nexus.tar.gz
    nexus_extracted_dir: /home/ubuntu/nexus
    nexus_dir: /usr/local/nexus

  tasks:
  - name: update apt
#    command: apt-get update
    apt: update_cache=yes cache_valid_time=3600
    become: yes

  - name: install wget
    apt: pkg='wget' state=present 

  - name: install jdk 8
    apt: pkg='openjdk-8-jdk' state=present
    become: yes

  - name: set JDK 8 as a default alternative
    command: update-alternatives --config java 
    become: yes

  - name: create "nexus" group
    group: name=nexus 
    become: yes

  - name: create "nexus" user
    user: name=nexus group=nexus 
    become: yes

  - name: download nexus
    get_url: url={{nexus_download_url}} dest={{nexus_download_dest}}
    register: nexus_download

  - name: create {{nexus_extracted_dir}} directory
    file: path={{nexus_extracted_dir}} state=directory
    when: nexus_download.changed
    become: yes

  - name: extract nexus to {{nexus_extracted_dir}}
    command: tar -xvf {{nexus_download_dest}} -C {{nexus_extracted_dir}} --strip-components=1
    when: nexus_download.changed
    become: yes

  - name: move nexus to {{nexus_dir}} directory
    command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
    when: nexus_download.changed
    become: yes

  - name: make {{nexus_dir}} directory property of "nexus" user/group
    file: path={{nexus_dir}} group=nexus owner=nexus recurse=true
    become: yes

  - name: make nexus runned by "nexus" user
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="#RUN_AS_USER=" line="RUN_AS_USER=nexus" backrefs=true
    become: yes

  - name: set NEXUS_HOME
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{nexus_dir}}" backrefs=true
    become: yes

  - name: create nexus piddir
    file: path=/var/run/nexus state=directory group=nexus owner=nexus
    become: yes

  - name: set nexus pidir
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true
    become: yes

  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/etc/init.d/nexus state=link
    become: yes

  - name: configure runlevel links for nexus
    command: update-rc.d nexus defaults
    become: yes

  - name: set nexus working directory
    lineinfile: dest={{nexus_dir}}/conf/nexus.properties regexp="^nexus-work=" line="nexus-work=${bundleBasedir}/work/nexus"
    become: yes

  - name: start nexus
    service: name=nexus state=started pattern={{nexus_dir}}
    become: yes
